
package soap.hr;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HRSoapService", targetNamespace = "http://admin.client.services.server/", wsdlLocation = "http://192.168.1.96:8080/Access%5Fwar/server.services/HRSoap?wsdl")
public class HRSoapService
    extends Service
{

    private final static URL HRSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException HRSOAPSERVICE_EXCEPTION;
    private final static QName HRSOAPSERVICE_QNAME = new QName("http://admin.client.services.server/", "HRSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.96:8080/Access%5Fwar/server.services/HRSoap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HRSOAPSERVICE_WSDL_LOCATION = url;
        HRSOAPSERVICE_EXCEPTION = e;
    }

    public HRSoapService() {
        super(__getWsdlLocation(), HRSOAPSERVICE_QNAME);
    }

    public HRSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HRSOAPSERVICE_QNAME, features);
    }

    public HRSoapService(URL wsdlLocation) {
        super(wsdlLocation, HRSOAPSERVICE_QNAME);
    }

    public HRSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HRSOAPSERVICE_QNAME, features);
    }

    public HRSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HRSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HRSoap
     */
    @WebEndpoint(name = "HRSoapPort")
    public HRSoap getHRSoapPort() {
        return super.getPort(new QName("http://admin.client.services.server/", "HRSoapPort"), HRSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HRSoap
     */
    @WebEndpoint(name = "HRSoapPort")
    public HRSoap getHRSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://admin.client.services.server/", "HRSoapPort"), HRSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HRSOAPSERVICE_EXCEPTION!= null) {
            throw HRSOAPSERVICE_EXCEPTION;
        }
        return HRSOAPSERVICE_WSDL_LOCATION;
    }

}
