
package soap.security;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SecuritySOAPService", targetNamespace = "http://admin.client.services.server/", wsdlLocation = "http://localhost:8080/server.services/SecuritySOAP?wsdl")
public class SecuritySOAPService
    extends Service
{

    private final static URL SECURITYSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECURITYSOAPSERVICE_EXCEPTION;
    private final static QName SECURITYSOAPSERVICE_QNAME = new QName("http://admin.client.services.server/", "SecuritySOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/server.services/SecuritySOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECURITYSOAPSERVICE_WSDL_LOCATION = url;
        SECURITYSOAPSERVICE_EXCEPTION = e;
    }

    public SecuritySOAPService() {
        super(__getWsdlLocation(), SECURITYSOAPSERVICE_QNAME);
    }

    public SecuritySOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SECURITYSOAPSERVICE_QNAME, features);
    }

    public SecuritySOAPService(URL wsdlLocation) {
        super(wsdlLocation, SECURITYSOAPSERVICE_QNAME);
    }

    public SecuritySOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SECURITYSOAPSERVICE_QNAME, features);
    }

    public SecuritySOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecuritySOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SecuritySOAP
     */
    @WebEndpoint(name = "SecuritySOAPPort")
    public SecuritySOAP getSecuritySOAPPort() {
        return super.getPort(new QName("http://admin.client.services.server/", "SecuritySOAPPort"), SecuritySOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecuritySOAP
     */
    @WebEndpoint(name = "SecuritySOAPPort")
    public SecuritySOAP getSecuritySOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://admin.client.services.server/", "SecuritySOAPPort"), SecuritySOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SECURITYSOAPSERVICE_EXCEPTION!= null) {
            throw SECURITYSOAPSERVICE_EXCEPTION;
        }
        return SECURITYSOAPSERVICE_WSDL_LOCATION;
    }

}
