
package soap.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SecuritySOAP", targetNamespace = "http://admin.client.services.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecuritySOAP {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "securityMethods", targetNamespace = "http://admin.client.services.server/", className = "soap.security.SecurityMethods")
    @ResponseWrapper(localName = "securityMethodsResponse", targetNamespace = "http://admin.client.services.server/", className = "soap.security.SecurityMethodsResponse")
    @Action(input = "http://admin.client.services.server/SecuritySOAP/securityMethodsRequest", output = "http://admin.client.services.server/SecuritySOAP/securityMethodsResponse")
    public Object securityMethods(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        AccountDATA arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        CardDATA arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        DeviceDATA arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        RightDATA arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        RoleDATA arg5);

}
