
package soap.technical;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TechnicalSOAP", targetNamespace = "http://admin.client.services.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TechnicalSOAP {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "technicalMethods", targetNamespace = "http://admin.client.services.server/", className = "soap.technical.TechnicalMethods")
    @ResponseWrapper(localName = "technicalMethodsResponse", targetNamespace = "http://admin.client.services.server/", className = "soap.technical.TechnicalMethodsResponse")
    @Action(input = "http://admin.client.services.server/TechnicalSOAP/technicalMethodsRequest", output = "http://admin.client.services.server/TechnicalSOAP/technicalMethodsResponse")
    public Object technicalMethods(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        DeviceDATA arg1);

}
