
package soap.reception;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ReceptionSOAP", targetNamespace = "http://admin.client.services.server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReceptionSOAP {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "receptionMethods", targetNamespace = "http://admin.client.services.server/", className = "soap.reception.ReceptionMethods")
    @ResponseWrapper(localName = "receptionMethodsResponse", targetNamespace = "http://admin.client.services.server/", className = "soap.reception.ReceptionMethodsResponse")
    @Action(input = "http://admin.client.services.server/ReceptionSOAP/receptionMethodsRequest", output = "http://admin.client.services.server/ReceptionSOAP/receptionMethodsResponse")
    public Object receptionMethods(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        GuestDATA arg1);

}
